import os
import time

print ('V/')
time.sleep(0.5)
os.system('clear')
print ('V|')
time.sleep(0.5)
os.system('clear')
print ('VA/')
time.sleep(0.5)
os.system('clear')
print ('VA|')
time.sleep(0.5)
os.system('clear')
print ('VAL/')
time.sleep(0.5)
os.system('clear')
print ('VAL|')
time.sleep(0.5)
os.system('clear')
print ('VALD/')
time.sleep(0.5)
os.system('clear')
print ('VALDO|')
time.sleep(0.5)
os.system('clear')
print ('VALDO/')
time.sleep(0.5)
os.system('clear')
print ('VALDO|')
time.sleep(0.5)
os.system('clear')
print ('VALDO R /')
time.sleep(0.5)
os.system('clear')
print ('VALDO T|')
time.sleep(0.5)
os.system('clear')
print ('VALDO TA/')
time.sleep(0.5)
os.system('clear')
print ('VALDO TA|')
time.sleep(0.5)
os.system('clear')
print ('VALDO TA/')
time.sleep(0.5)
os.system('clear')
print ('VALDO TAR|')
time.sleep(0.5)
os.system('clear')
print ('VALDO TAR/')
time.sleep(0.5)
os.system('clear')
print ('VALDO TARO|')
time.sleep(0.5)
os.system('clear')
print ('VALDO TAROR/')
time.sleep(0.5)
os.system('clear')
print ('VALDO TAROR|')
time.sleep(0.5)
os.system('clear')
print ('VALDO TAROR/')
time.sleep(0.5)
os.system('clear')
print ('VALDO TARORE|')
time.sleep(0.5)
os.system('clear')
print ('VALDO TAROREH/')
time.sleep(0.5)
os.system('clear')
print ('VALDO TAROREH')
time.sleep(0.5)
